version: '3'

services:
  server:
    image: frdserver
    ports:
      - "8080:8080"
  environment:
    - SECRET=12345
    - DB_NAME=c29_frd
    - DB_USERNAME=postgres
    - DB_PASSWORD=12345
    - DB_HOST=DB_HOST
  links:
    - db
  db:


